### ISSUE TITLE
DrpTV updates, round 50557k

### ISSUE THREAD

**Issue by Saurutobi** [LbKStudios/lbkstudios-main#141] opened 2015-01-05 18:41 UTC
~~1.Main Player controller doesn't pop up~~
~~2.Fullscreen option on video sliders~~ 
~~3.About Us Header and Logo centered more~~
~~4.Bio Page: Link Ashlea Harnden image to http://www.imdb.com/name/nm5101744/?ref_=fn_al_nm_1~~
~~5.Bio Page: Link Joshua Harnden image to http://www.imdb.com/name/nm3341527/?ref_=fn_al_nm_1~~
~~6.Testimonials: Link Cash's name, not company~~
~~7.Testimonials: Link Lori Rothschild's name, not company.~~
~~8.Contact: Dimensions seem too skinny, match length of “For more information on drpTV,….”~~
~~9.Home page videos under "view all" seems to have black boxes~~
~~10.Contact form not emailing~~

**Comment by Harmonickey** [comment] 2015-01-05 21:19
Check of the fullscreen stuff.  Should work well.

**Comment by Harmonickey** [comment] 2015-01-06 01:58
I think you can do the overlay part with the View All videos in /videos.

The problem is that the videos are defaulted to a black screen with a play button, but Ziwe wants a picture of which you can click and the video plays.

I know I can do this, but I think it'd be cool if you did.  I'll lay out a good way to do it.

1. Wrap each video player in a div.  Add a background to each div.
2. Create a css :hover class that you apply to each div in question.  This :hover class will make the div have background: none; 

It would be easier if we had direct access to the video tag associated with the video players, instead of shortcodes, or at least a way to add ids/classes. That way we could do it the opposite (and in my opinion the more efficient) way.  
1. Wrap each video player in a div.  Add a background to each div.  Make each video player have opaque: 0;
2. Create a css :hover class that you apply to each div in question. This :hover class will make the video have opaque: 1;
3 (optional). You could make the opaque quality have an animated effect, CSS3 can do this.

**Comment by Harmonickey** [comment] 2015-01-06 02:01
Wait... nevermind.  VideoJS has an option for this already...
[videojs poster="http://video-js.zencoder.com/oceans-clip.png"]

**Comment by Harmonickey** [comment] 2015-01-06 02:13
The videos now have backgrounds :)

**Comment by Harmonickey** [comment] 2015-01-06 02:21
I would recommend setting the width of the contact form to 581px instead of 50%.

The width of the paragraph text is 581px, you can see if you set display: inline-block; width: auto;

**Comment by Saurutobi** [comment] 2015-01-07 06:42
Alex, the video player, when fullscreen, should play with sound. when sound is off and fullscreen is clicked, it stays off and no controls are there. To avoid having to put controls there, we should enable sound always on fullscreen.

**Comment by Harmonickey** [comment] 2015-01-07 14:49
agreed

On Wed, Jan 7, 2015 at 12:42 AM, Saurutobi <notifications@github.com> wrote:

> Alex, the video player, when fullscreen, should play with sound. when
> sound is off and fullscreen is clicked, it stays off and no controls are
> there. To avoid having to put controls there, we should enable sound always
> on fullscreen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/141#issuecomment-68984948>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*

**Comment by Harmonickey** [comment] 2015-01-07 15:32
I made it do that, now I sent a message to the developer asking if he knows how to fix the initial clicking problem.

**Comment by Harmonickey** [comment] 2015-01-10 20:13
I have a feeling that the problems with Ziwe have to do with the fact that she's using a significantly larger screen than me (us?).  Can you test on your differently sized screens?  Do the video controls show then?

**Comment by Saurutobi** [comment] 2015-01-11 02:52
I'm having problems with the fullscreen controls. on my pc, neither firefox nor chrome shows those purple controls, but chrome shows it's own set of controls. I txted you a pic. Also, no problems with About Us stuff

**Comment by Harmonickey** [comment] 2015-01-11 02:59
Added CSS to disable the fullscreen controls that automatically pop-up.  Added at the top of the CSS Styles area of the Appearance -> Customize dashboard screen.

**Comment by Harmonickey** [comment] 2015-01-11 02:59
Not sure yet how to get the purple controls to show up on fullscreen...

**Comment by Harmonickey** [comment] 2015-01-11 03:53
Check it now.  Looks pretty good.

**Comment by Harmonickey** [comment] 2015-01-11 04:09
I also added background "poster" attributes to all the videos in the project pages, they were blank previously.  She would have likely commented on it.

**Comment by Saurutobi** [comment] 2015-01-12 12:42
I'm having trouble with the contact form emailing. Can you take a peek? I used the example from w3 so it should work, but it's not.

**Comment by Harmonickey** [comment] 2015-01-12 17:55
It requires user authentication.  Send the form data to a php script and send that way instead, that's how I usually do it at Comcast and other stuff.  Here's an article saying the same thing.

http://www.javascript-coder.com/javascript-form/javascript-email-form.phtml

**Comment by Harmonickey** [comment] 2015-01-13 00:44
Contact form now works.  Check it out.

There is one issue where it throws the form around the screen when it's submitted.  That can be fixed with a simple redirect option instead.

**Comment by Harmonickey** [comment] 2015-01-13 00:54
Actually, not sure how to fix the weird jumpy behavior...

**Comment by Harmonickey** [comment] 2015-01-13 05:33
I think I made a fix for this, check it out.

**Comment by Saurutobi** [comment] 2015-01-13 14:18
saw, typed, good

**Comment by Harmonickey** [comment] 2015-01-14 03:05
We should probably send an email update at this point then.

**Closed** 2015-01-14 03:06 UTC
Labels: Ready for Review, type-Story

**Comment by Saurutobi** [comment] 2015-01-14 03:14
im at work, i cant do it. can you please? Ill be back home in 2 hrs so i
can do it then if u dont wanna

**Comment by Harmonickey** [comment] 2015-01-14 03:16
Fine, I'll do it :P

On Tue, Jan 13, 2015 at 9:14 PM, Saurutobi <notifications@github.com> wrote:

> im at work, i cant do it. can you please? Ill be back home in 2 hrs so i
> can do it then if u dont wanna
>
> On Tue, Jan 13, 2015 at 10:05 PM, Alex Ayerdi <notifications@github.com>
> wrote:
>
> > We should probably send an email update at this point then.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/LbKStudios/lbkstudios-main/issues/141#issuecomment-69862415>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/lbkstudios-main/issues/141#issuecomment-69862967>
> .
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AlexanderAyerdi2015
*@u.northwestern.edu <AlexanderAyerdi@u.northwestern.edu>mobile:
1-269-267-3752*
